name: release-container

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: notbobthebuilder/fpm
jobs:
  release-on-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: NotBobTheBuilder/fpm
          ref: main
      - name: build
        run: make docker-release-everything
      - name: registry login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        run: |
          docker image tag fpm:latest ghcr.io/notbobthebuilder/fpm:latest
          docker image push ghcr.io/notbobthebuilder/fpm:latest
