name: release-container

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: notbobthebuilder/fpm
jobs:
  build-containers:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu_latest
          - arch: arm64v8
            distro: ubuntu_latest
          - arch: x86_64
            distro: ubuntu_latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          repository: NotBobTheBuilder/fpm
          ref: main
      - name: build
        uses: NotBobTheBuilder/run-on-arch-action@amd64-support
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          dockerRunArgs: |
            --volume "${PWD}:/fpm"
          run: |
            apt-get update
            apt-get install -y make ca-certificates curl gnupg
            install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            chmod a+r /etc/apt/keyrings/docker.gpg
            echo \
            "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
            tee /etc/apt/sources.list.d/docker.list > /dev/null
            apt-get update
            apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            cd /fpm
            make docker-release-everything
      - name: registry login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        run: |
          docker image tag fpm:latest ghcr.io/notbobthebuilder/fpm:latest-${{ matrix.arch }}
          docker image push ghcr.io/notbobthebuilder/fpm:latest-${{ matrix.arch }}
  push-manifest:
    runs-on: ubuntu-latest
    needs: build-containers
    permissions:
      contents: read
      packages: write
    steps:
      - name: registry login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        run: |
          docker manifest create \
          ghcr.io/notbobthebuilder/fpm:latest \
          --amend ghcr.io/notbobthebuilder/fpm:latest-amd64 \
          --amend ghcr.io/notbobthebuilder/fpm:latest-aarch64
          --amend ghcr.io/notbobthebuilder/fpm:latest-arm64v8
          docker manifest push ghcr.io/notbobthebuilder/fpm:latest
